sudo: required

language: go

go:
- '1.10'

env:
  global:
  - "PATH=$PATH:$HOME/local/bin"

before_install:
- curl -s https://git.io/install-protoc | bash -s 3.5.1
- make deps

script:
- make build && make test && make build-docker

after_success:
  # Discord notification
  - curl -sL https://git.io/ss-notify-discord-travis | bash -s success $WEBHOOK_URL
  
  # push to docker
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $TRAVIS_REPO_SLUG:dev;
    curl -sL https://git.io/ss-notify-discord-docker | bash -s $TRAVIS_REPO_SLUG:dev $DOCKERHUB_WEBHOOK;
    fi
  - if [ $TRAVIS_TAG ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag $TRAVIS_REPO_SLUG:dev $TRAVIS_REPO_SLUG:latest;
    docker push $TRAVIS_REPO_SLUG:latest;
    curl -sL https://git.io/ss-notify-discord-docker | bash -s $TRAVIS_REPO_SLUG:latest $DOCKERHUB_WEBHOOK;
    docker tag $TRAVIS_REPO_SLUG $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1};
    docker push $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1};
    curl -sL https://git.io/ss-notify-discord-docker | bash -s $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1} $DOCKERHUB_WEBHOOK;
    fi

after_failure:
  # Discord notification
  - curl -sL https://git.io/notify-discord-travis | bash -s failure $WEBHOOK_URL
