sudo: required

language: go

go:
- '1.10'

env:
  global:
  - "PATH=$PATH:$HOME/local/bin"

before_install:
- curl -s https://raw.githubusercontent.com/soupstore/build-scripts/master/install-protoc.sh | bash -s 3.5.1
- make deps

script:
- make build
- make test
- make build-docker

after_success:
  # Discord notification
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  # push to docker
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $TRAVIS_REPO_SLUG:dev;
    ./.travis/dockerhub-notification.sh $TRAVIS_REPO_SLUG:dev $DOCKERHUB_WEBHOOK;
    fi
  - if [ $TRAVIS_TAG ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag $TRAVIS_REPO_SLUG:dev $TRAVIS_REPO_SLUG:latest;
    docker push $TRAVIS_REPO_SLUG:latest;
    ./.travis/dockerhub-notification.sh $TRAVIS_REPO_SLUG:latest $DOCKERHUB_WEBHOOK;
    docker tag $TRAVIS_REPO_SLUG $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1};
    docker push $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1};
    ./.travis/dockerhub-notification.sh $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1} $DOCKERHUB_WEBHOOK;
    fi

after_failure:
  # Discord notification
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
